version : "3"

services:
  solid-tests:
    image: solid/tests:latest
    container_name: solid-tests
    build:
      context: ../src
      dockerfile: ./Daycoval.Solid.Test/Dockerfile
    command: dotnet test  

  solid-sqlserver:
    container_name: solid-sqlserver
    build:
      context: ../docker
      dockerfile: ./sqlserver/Dockerfile
    environment:
      MSSQL_SA_PASSWORD: "Solid@123."
      MSSQL_PID: "Express"
      ACCEPT_EULA: "Y"

    ports:
      - '1433:1433'

  solid-pedido-api:
    image: solid/pedido-api:latest
    container_name: solid-pedido-api
    build:
      context: ../src
      dockerfile: ./Daycoval.Solid.Pedido.API/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIROMENT=Development
      - ASPNETCORE_URLS=http://*:5001
    depends_on:
      - solid-sqlserver
      - solid-tests

